---
# MOMNIT CONFIGURATION

- name: download monit if doesnt exists
  local_action: >
    get_url 
      url="{{monit_download_url}}/{{monit_version}}/{{monit_package}}"
      dest="{{monit_download_dir}}/{{monit_package}}"
  tags: download

- name: create monit directories
  file:
    path="{{item}}"
    state=directory
  with_items:
    - "{{monit_installation_dir}}/rc/"
    - "{{monit_installation_dir}}/rc/log/"
    - "{{monit_installation_dir}}/rc/events"
    - "{{monit_include_checks_dir}}"
    - "{{monit_include_scripts_dir}}"

- name: unzip monit file on destiny
  unarchive: 
    src="{{monit_download_dir}}/{{monit_package}}"
    dest="{{monit_installation_dir}}/"
  tags: unpack

- name: create monitrc file
  template:
    src="./monitrc"
    dest="{{monit_installation_dir}}/monitrc"
    mode=0700
